import type { Store } from './api';

export const MOCK_STORES: Store[] = [
  {
    storeId: 'store_001',
    storeName: 'セブン-イレブン 渋谷道玄坂店',
    address: '東京都渋谷区道玄坂1-12-1',
    lat: 35.6591,
    lng: 139.6989,
    distanceKm: 0.3,
    convenienceBrand: 'seven_eleven',
    series: [
      {
        seriesId: 'series_001',
        title: '一番くじ ドラゴンボール STRONG CHAINS!!',
        price: 790,
        releaseDate: '2026-03-15',
        totalTickets: 80,
        remainingTickets: 23,
        status: 'on_sale',
        prizes: [
          { rank: 'A', name: '孫悟空 フィギュア', quantity: 1, remaining: 1 },
          { rank: 'B', name: 'ベジータ フィギュア', quantity: 2, remaining: 1 },
          { rank: 'C', name: 'アクリルスタンド', quantity: 8, remaining: 4 },
          { rank: 'D', name: 'クリアファイルセット', quantity: 10, remaining: 6 },
          { rank: 'ラスト', name: '超特大フィギュア', quantity: 1, remaining: 1 },
        ],
      },
      {
        seriesId: 'series_002',
        title: '一番くじ 呪術廻戦 ～壊玉・玉折～',
        price: 750,
        releaseDate: '2026-04-01',
        totalTickets: 70,
        remainingTickets: 70,
        status: 'upcoming',
        prizes: [
          { rank: 'A', name: '五条悟 フィギュア', quantity: 1, remaining: 1 },
          { rank: 'B', name: '宿儺 フィギュア', quantity: 2, remaining: 2 },
          { rank: 'C', name: 'ラバーストラップ', quantity: 10, remaining: 10 },
        ],
      },
    ],
  },
  {
    storeId: 'store_002',
    storeName: 'ローソン 渋谷センター街店',
    address: '東京都渋谷区宇田川町31-2',
    lat: 35.6614,
    lng: 139.6983,
    distanceKm: 0.6,
    convenienceBrand: 'lawson',
    series: [
      {
        seriesId: 'series_003',
        title: '一番くじ ワンピース ～新世界編～',
        price: 790,
        releaseDate: '2026-02-20',
        totalTickets: 80,
        remainingTickets: 5,
        status: 'on_sale',
        prizes: [
          { rank: 'A', name: 'ルフィ ギア5フィギュア', quantity: 1, remaining: 0 },
          { rank: 'B', name: 'ゾロ フィギュア', quantity: 2, remaining: 1 },
          { rank: 'C', name: 'ナミ フィギュア', quantity: 3, remaining: 1 },
          { rank: 'D', name: 'タオル', quantity: 8, remaining: 2 },
          { rank: 'ラスト', name: '超特大ルフィ', quantity: 1, remaining: 1 },
        ],
      },
    ],
  },
  {
    storeId: 'store_003',
    storeName: 'ファミリーマート 渋谷公園通り店',
    address: '東京都渋谷区宇田川町12-7',
    lat: 35.6628,
    lng: 139.6974,
    distanceKm: 0.9,
    convenienceBrand: 'family_mart',
    series: [
      {
        seriesId: 'series_004',
        title: '一番くじ 鬼滅の刃 ～柱稽古編～',
        price: 790,
        releaseDate: '2026-03-10',
        totalTickets: 80,
        remainingTickets: 42,
        status: 'on_sale',
        prizes: [
          { rank: 'A', name: '炭治郎 フィギュア', quantity: 1, remaining: 1 },
          { rank: 'B', name: '禰豆子 フィギュア', quantity: 2, remaining: 2 },
          { rank: 'C', name: '煉獄 フィギュア', quantity: 3, remaining: 2 },
          { rank: 'D', name: 'マグカップ', quantity: 6, remaining: 4 },
          { rank: 'E', name: 'クリアファイル', quantity: 10, remaining: 7 },
        ],
      },
      {
        seriesId: 'series_005',
        title: '一番くじ 進撃の巨人 FINAL',
        price: 850,
        releaseDate: '2026-01-15',
        totalTickets: 60,
        remainingTickets: 0,
        status: 'sold_out',
        prizes: [
          { rank: 'A', name: 'エレン フィギュア', quantity: 1, remaining: 0 },
          { rank: 'B', name: 'リヴァイ フィギュア', quantity: 2, remaining: 0 },
        ],
      },
    ],
  },
  {
    storeId: 'store_004',
    storeName: 'セブン-イレブン 原宿表参道店',
    address: '東京都渋谷区神宮前4-3-2',
    lat: 35.6673,
    lng: 139.7044,
    distanceKm: 1.4,
    convenienceBrand: 'seven_eleven',
    series: [
      {
        seriesId: 'series_006',
        title: '一番くじ 僕のヒーローアカデミア NEXT GENERATIONS!',
        price: 750,
        releaseDate: '2026-03-20',
        totalTickets: 80,
        remainingTickets: 80,
        status: 'upcoming',
        prizes: [
          { rank: 'A', name: 'デク フィギュア', quantity: 1, remaining: 1 },
          { rank: 'B', name: 'オールマイト フィギュア', quantity: 2, remaining: 2 },
          { rank: 'C', name: 'アクリルスタンドセット', quantity: 8, remaining: 8 },
        ],
      },
    ],
  },
  {
    storeId: 'store_005',
    storeName: 'ローソン 代官山蔦屋書店前店',
    address: '東京都渋谷区猿楽町17-5',
    lat: 35.6488,
    lng: 139.7031,
    distanceKm: 2.1,
    convenienceBrand: 'lawson',
    series: [
      {
        seriesId: 'series_007',
        title: '一番くじ SPY×FAMILY MISSION:8',
        price: 700,
        releaseDate: '2026-03-01',
        totalTickets: 70,
        remainingTickets: 18,
        status: 'on_sale',
        prizes: [
          { rank: 'A', name: 'アーニャ フィギュア', quantity: 1, remaining: 1 },
          { rank: 'B', name: 'ロイド フィギュア', quantity: 2, remaining: 1 },
          { rank: 'C', name: 'ヨル フィギュア', quantity: 3, remaining: 2 },
          { rank: 'D', name: 'ぬいぐるみ', quantity: 5, remaining: 3 },
          { rank: 'E', name: 'タオルセット', quantity: 8, remaining: 5 },
        ],
      },
    ],
  },
];
